config/routes.rb
Rails.application.routes.draw do
  resources :things, except: [:show, :destroy]

  root to: "things#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :thing
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  def index
    @things = Thing.all
  end

  def new
    form Thing::Create
  end

  def create
    run Thing::Create do |op|
      return redirect_to things_url
    end

    render :new
  end

  def edit
    form Thing::Update
    render :new
  end

  def update
    run Thing::Update do |op|
      return redirect_to things_url
    end

    render :new
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gemgem</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/things/index.html.erb
<p>
  <%= link_to 'Add a thing', new_thing_path, class: "btn btn-primary" %>
</p>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= concept("thing/cell/table_rows") %>
  </tbody>
</table>

app/views/things/new.html.erb
<h1>Add a thing</h1>

<%= simple_form_for @form do |f| %>
  <%= f.input :name, readonly: @form.readonly?(:name) %>
  <%= f.input :description %>
  <%= f.button :submit, "Save" %>
<% end %>